#开发期使用的子配置文件，application-dev
#自定义配置项：sky
sky:
  #数据库相关配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  #jwt令牌相关配置
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: skyrestaurant
  #阿里云OSS相关配置
  alioss:
    access-key-id: LTAI5tSr84daqHZnywPDBiwM
    access-key-secret: DDb2uKZIrLnJ2zUfiYC5JeBSwcmSbE
    bucket-name: the-sky-takeout
    endpoint: oss-cn-beijing.aliyuncs.com
